package net.lingyun.ultraui.android.components

import org.junit.Assert.assertEquals
import org.junit.Assert.assertThrows
import org.junit.Test

/**
 * Verifies [upBarcodeEncode] reproduces uview-plus `u-barcode` byte-for-byte. Expected module
 * strings were generated by running the upstream `encodeBarcode` family in Node for each format.
 */
class UPBarcodeEncoderTest {
    private data class Case(val value: String, val format: String, val bits: String)

    private val cases = listOf(
        Case("Hello123", "CODE128", "110100100001100010100010110010000110010100001100101000010001111010100111001101100111001011001011100100011011101100011101000000"),
        Case("ULTRA-ui", "auto", "110100100001101110111010001101110110111000101100010111010100011000100110111001001111001010000110100100100001101100011101000000"),
        Case("CODE39TEST", "CODE39", "10001011101110101110111010001010111010111010001010101110001011101110101110001010111011100010101010111000101110101010111011100010111010111000101010111010111000101010111011100010100010111011101"),
        Case("5901234123457", "EAN13", "10100010110100111011001100100110111101001110101010110011011011001000010101110010011101000100101"),
        Case("96385074", "EAN8", "1010001011010111101111010110111010101001110111001010001001011100101"),
        Case("12345", "EAN5", "10110011001010010011010111101010100011010110001"),
        Case("42", "EAN2", "10110100011010010011"),
        Case("03600029145", "UPCA", "10100011010111101010111100011010001101000110101010110110011101001100110101110010011101101100101"),
        Case("01234565", "UPCE", "101011001100110110111101010001101100010101111010101101"),
    )

    @Test
    fun encodingsMatchUpstreamBarcode() {
        for (case in cases) {
            assertEquals("bits for '${case.value}' (${case.format})", case.bits, upBarcodeEncode(case.value, case.format))
        }
    }

    @Test
    fun autoFormatFallsBackToCode128() {
        assertEquals(upBarcodeEncode("Hello123", "CODE128"), upBarcodeEncode("Hello123", "auto"))
    }

    @Test
    fun invalidInputThrowsLikeUpstream() {
        assertThrows(IllegalArgumentException::class.java) { upBarcodeEncode("123", "EAN13") }
        assertThrows(IllegalArgumentException::class.java) { upBarcodeEncode("中文", "CODE128") }
        assertThrows(IllegalArgumentException::class.java) { upBarcodeEncode("1234567890123", "EAN13") }
    }
}
