package net.lingyun.ultraui.android.components

import net.lingyun.ultraui.android.core.UPRawValue
import net.lingyun.ultraui.android.core.UPStyleInput

public data class UPCalendarProps(
    val title: String = "日期选择",
    val showTitle: Boolean = true,
    val showSubtitle: Boolean = true,
    val mode: String = "single",
    val startText: String = "开始日期",
    val endText: String = "结束日期",
    val customList: List<UPRawValue> = emptyList(),
    val color: String = "#3c9cff",
    val minDate: UPRawValue = 0,
    val maxDate: UPRawValue = 0,
    val defaultDate: UPRawValue? = null,
    val maxCount: UPRawValue = Long.MAX_VALUE,
    val rowHeight: UPRawValue = 56,
    val formatter: UPRawValue? = null,
    val showLunar: Boolean = false,
    val showMark: Boolean = true,
    val confirmText: String = "确定",
    val confirmDisabledText: String = "确定",
    val show: Boolean = false,
    val closeOnClickOverlay: Boolean = false,
    val readonly: Boolean = false,
    val showConfirm: Boolean = true,
    val maxRange: UPRawValue = Long.MAX_VALUE,
    val rangePrompt: String = "",
    val showRangePrompt: Boolean = true,
    val allowSameDay: Boolean = false,
    val rangeResultMode: String = "all",
    val enableTime: Boolean = false,
    val timePrecision: String = "minute",
    val defaultTime: UPRawValue = "",
    val round: UPRawValue = 0,
    val monthNum: UPRawValue = 3,
    val monthSwitch: Boolean = false,
    val showToday: Boolean = true,
    val todayColor: String = "#3c9cff",
    val weekText: List<String> = listOf("日", "一", "二", "三", "四", "五", "六"),
    val forbidDays: List<UPRawValue> = emptyList(),
    val forbidDaysToast: String = "",
    val monthFormat: String = "YYYY年MM月",
    val pageInline: Boolean = false,
    val overlay: Boolean = true,
    val duration: UPRawValue = 300,
    val overlayStyle: UPStyleInput = emptyMap<String, UPRawValue>(),
    val overlayOpacity: UPRawValue = 0.5,
    val zIndex: UPRawValue = 10075,
    val safeAreaInsetBottom: Boolean = true,
    val safeAreaInsetTop: Boolean = false,
    val bgColor: String = "",
    val customStyle: UPStyleInput = emptyMap<String, UPRawValue>(),
)

public data class UPCalendarEvent(
    val value: UPRawValue,
    val year: Int,
    val month: Int,
    val day: Int,
    val mode: String,
    val selected: List<UPRawValue> = emptyList(),
)
