#!/usr/bin/env python3
"""Generate the deterministic Android UPIcon glyph catalog from uview-plus icons.js."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

ENTRY = re.compile(
    r"(?P<quote>['\"])(?P<name>uicon-[^'\"]+)(?P=quote)\s*:\s*"
    r"(?P<glyph_quote>['\"])(?P<glyph>\\u[0-9a-fA-F]{4})(?P=glyph_quote)",
)
PREFIX = "uicon-"


def parse_entries(source: Path) -> list[tuple[str, int]]:
    entries = []
    seen = set()
    for match in ENTRY.finditer(source.read_text(encoding="utf-8")):
        upstream_name = match.group("name")
        name = upstream_name.removeprefix(PREFIX)
        if not name or name in seen:
            raise ValueError(f"Duplicate or malformed uview-plus icon name: {upstream_name}")
        seen.add(name)
        entries.append((name, int(match.group("glyph")[2:], 16)))
    if not entries:
        raise ValueError(f"No uview-plus icon entries found in {source}")
    return sorted(entries, key=lambda entry: entry[0])


def render(entries: list[tuple[str, int]]) -> str:
    lines = [
        "// Generated by tools/generate_upicon_catalog.py. Do not edit manually.",
        "// Source: uview-plus/src/uni_modules/uview-plus/components/u-icon/icons.js",
        "package net.lingyun.ultraui.android.components",
        "",
        "/** Pinned uview-plus `uicon-*` glyphs rendered by the bundled font. */",
        "public object UPIconGlyphs {",
        "    private val glyphs: Map<String, Char> = mapOf(",
    ]
    lines.extend(f'        "{name}" to \'\\u{code_point:04x}\',' for name, code_point in entries)
    lines.extend(
        [
            "    )",
            "",
            "    /** The 213 names from the pinned uview-plus `icons.js` catalog. */",
            "    public val names: Set<String>",
            "        get() = glyphs.keys",
            "",
            "    /** Resolves a bare uview name or its single `uicon-` prefixed spelling. */",
            "    public fun codePoint(name: String): Char? = glyphs[name.removePrefix(\"uicon-\")]",
            "}",
            "",
        ],
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path, help="Pinned uview-plus components/u-icon/icons.js")
    parser.add_argument("output", type=Path, help="Generated Kotlin output path")
    args = parser.parse_args()

    output = args.output
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render(parse_entries(args.source)), encoding="utf-8")


if __name__ == "__main__":
    main()
